version: '3'
services:
  api:
    image: 'com.pillar/artisan-bootcamp-project'
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
      BANKSERVICE_HOST: 'fake-bank-service'
      BANKSERVICE_PORT: '8080'
    depends_on:
      - "mysql"
  mysql:
    image: 'mysql:8.0.13'
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'cc_processing'

  mongodb:
    image: 'mongo:latest'
    restart: always
    ports:
      - "27017:27017"

  fake-bank-service:
    image: 'com.pillar/fake-bank-service'
    ports:
      - "5000:8080"